use serde::{Deserialize, Serialize};
use tree_sitter::{Node, Parser};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct FilterConfig {
    pub minimum_bytes: usize,
    pub maximum_bytes: usize,
    pub maximum_comment_ratio: f64,
    /// Only the header is inspected for generator banners. Scanning the entire
    /// program would reject ordinary string literals that discuss generated code.
    pub generated_marker_scan_bytes: usize,
    pub generated_markers: Vec<String>,
}

impl Default for FilterConfig {
    fn default() -> Self {
        Self {
            minimum_bytes: 100,
            maximum_bytes: 16 * 1024 * 1024,
            maximum_comment_ratio: 0.5,
            generated_marker_scan_bytes: 8 * 1024,
            generated_markers: vec![
                "auto-generated".into(),
                "autogenerated".into(),
                "generated by".into(),
                "do not edit".into(),
                "@generated".into(),
            ],
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FilterRejection {
    TooSmall,
    TooLarge,
    InvalidUtf8,
    SyntaxError,
    CommentRatio,
    GeneratedBoilerplate,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum FilterDecision {
    Accept { comment_ratio: f64 },
    Reject(FilterRejection),
}

pub struct PythonFilter {
    parser: Parser,
    config: FilterConfig,
    generated_markers: Vec<Vec<u8>>,
}

impl PythonFilter {
    pub fn new(config: FilterConfig) -> Self {
        let mut parser = Parser::new();
        parser
            .set_language(&tree_sitter_python::LANGUAGE.into())
            .expect("tree-sitter-python language ABI must match tree-sitter");
        let generated_markers = config
            .generated_markers
            .iter()
            .map(|value| value.to_ascii_lowercase().into_bytes())
            .collect();
        Self {
            parser,
            config,
            generated_markers,
        }
    }

    pub fn evaluate(&mut self, source: &[u8]) -> FilterDecision {
        if source.len() < self.config.minimum_bytes {
            return FilterDecision::Reject(FilterRejection::TooSmall);
        }
        if source.len() > self.config.maximum_bytes {
            return FilterDecision::Reject(FilterRejection::TooLarge);
        }
        if std::str::from_utf8(source).is_err() {
            return FilterDecision::Reject(FilterRejection::InvalidUtf8);
        }
        let header = &source[..source.len().min(self.config.generated_marker_scan_bytes)];
        if contains_ascii_case_insensitive(header, &self.generated_markers) {
            return FilterDecision::Reject(FilterRejection::GeneratedBoilerplate);
        }
        let Some(tree) = self.parser.parse(source, None) else {
            return FilterDecision::Reject(FilterRejection::SyntaxError);
        };
        if contains_syntax_error(tree.root_node()) {
            return FilterDecision::Reject(FilterRejection::SyntaxError);
        }
        let comment_bytes = count_comment_bytes(tree.root_node());
        let ratio = comment_bytes as f64 / source.len() as f64;
        if ratio > self.config.maximum_comment_ratio {
            return FilterDecision::Reject(FilterRejection::CommentRatio);
        }
        FilterDecision::Accept {
            comment_ratio: ratio,
        }
    }
}

fn contains_syntax_error(root: Node<'_>) -> bool {
    let mut stack = vec![root];
    while let Some(node) = stack.pop() {
        if node.is_error() || node.is_missing() || (node.has_error() && node.child_count() == 0) {
            return true;
        }
        let mut cursor = node.walk();
        stack.extend(node.children(&mut cursor));
    }
    false
}

fn contains_ascii_case_insensitive(source: &[u8], needles: &[Vec<u8>]) -> bool {
    needles.iter().any(|needle| {
        !needle.is_empty()
            && source.windows(needle.len()).any(|window| {
                window
                    .iter()
                    .zip(needle)
                    .all(|(left, right)| left.to_ascii_lowercase() == *right)
            })
    })
}

fn count_comment_bytes(root: Node<'_>) -> usize {
    let mut stack = vec![root];
    let mut bytes = 0;
    while let Some(node) = stack.pop() {
        if node.kind() == "comment" {
            bytes += node.end_byte().saturating_sub(node.start_byte());
            continue;
        }
        let mut cursor = node.walk();
        for child in node.children(&mut cursor) {
            stack.push(child);
        }
    }
    bytes
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accepts_valid_python_and_rejects_syntax() {
        let mut filter = PythonFilter::new(FilterConfig::default());
        let valid = b"def useful_function(value: int) -> int:\n    result = value * 2\n    return result\n\nprint(useful_function(21))\n";
        assert!(matches!(
            filter.evaluate(valid),
            FilterDecision::Accept { .. }
        ));

        let invalid = b"def useful_function(value: int) -> int:\n    if value > 2\n        return value\n# padding padding padding padding padding padding padding\n";
        assert_eq!(
            filter.evaluate(invalid),
            FilterDecision::Reject(FilterRejection::SyntaxError)
        );
    }

    #[test]
    fn rejects_generated_marker_case_insensitively() {
        let mut filter = PythonFilter::new(FilterConfig::default());
        let source = b"# THIS FILE IS AUTO-GENERATED; DO NOT EDIT\nvalue = 1\n# padding padding padding padding padding padding padding padding padding\n";
        assert_eq!(
            filter.evaluate(source),
            FilterDecision::Reject(FilterRejection::GeneratedBoilerplate)
        );
    }

    #[test]
    fn generator_words_outside_header_do_not_trigger_banner_filter() {
        let config = FilterConfig {
            generated_marker_scan_bytes: 32,
            ..FilterConfig::default()
        };
        let mut filter = PythonFilter::new(config);
        let source = b"value = 1\n# padding to leave header\nmessage = 'this text discusses code generated by a tool'\nprint(value, message)\n";
        assert!(matches!(
            filter.evaluate(source),
            FilterDecision::Accept { .. }
        ));
    }
}
