use super::{MAX_CANONICAL_BYTES, MIN_CANONICAL_BYTES};
use crate::error::{ProductError, Result};
use std::collections::BTreeSet;

pub(crate) const UTF8_BOM: &[u8] = b"\xEF\xBB\xBF";
const GENERATED_HEADER_BYTES: usize = 8192;
const GENERATED_MARKERS: &[&[u8]] = &[
    b"@generated",
    b"auto-generated",
    b"autogenerated",
    b"automatically generated",
    b"code generated",
    b"generated by",
    b"generated file",
    b"this file is generated",
    b"do not edit",
];
const PERMISSIVE_LICENSES: &[&str] = &[
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "Python-2.0",
    "Zlib",
];

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ParserFacts {
    pub dialect_accepted: bool,
    pub comment_ranges: Vec<ByteRange>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ByteRange {
    pub start: usize,
    pub end: usize,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ParserPolicyDecision {
    Accepted,
    Rejected(&'static str),
}

#[derive(Debug)]
pub(crate) struct DecodedPython {
    pub(crate) bytes: Vec<u8>,
    pub(crate) bom_removed: bool,
}

pub fn evaluate_parser_policy(
    canonical_bytes: &[u8],
    facts: &ParserFacts,
) -> Result<ParserPolicyDecision> {
    if !facts.dialect_accepted {
        return Ok(ParserPolicyDecision::Rejected("PYTHON_SYNTAX_REJECTED"));
    }
    let mut previous_end = 0;
    let mut comment_bytes = 0_usize;
    for range in &facts.comment_ranges {
        if range.start >= range.end
            || range.start < previous_end
            || range.end > canonical_bytes.len()
        {
            return Err(ProductError::integrity(
                "PARSER_FACTS_INVALID",
                "parser comment ranges are overlapping, unordered, empty, or out of bounds",
            ));
        }
        previous_end = range.end;
        comment_bytes = comment_bytes
            .checked_add(range.end - range.start)
            .ok_or_else(|| {
                ProductError::integrity("PARSER_FACTS_INVALID", "comment byte count overflowed")
            })?;
        let header_end = range.end.min(GENERATED_HEADER_BYTES);
        if range.start < header_end
            && contains_generated_marker(&canonical_bytes[range.start..header_end])
        {
            return Ok(ParserPolicyDecision::Rejected("GENERATED_MARKER"));
        }
    }
    if comment_bytes.saturating_mul(2) > canonical_bytes.len() {
        return Ok(ParserPolicyDecision::Rejected("COMMENT_RATIO_EXCEEDED"));
    }
    Ok(ParserPolicyDecision::Accepted)
}
pub(crate) fn canonical_size_allowed(bytes: usize) -> bool {
    (MIN_CANONICAL_BYTES..=MAX_CANONICAL_BYTES).contains(&bytes)
}

pub(crate) fn decode_python(raw: &[u8]) -> std::result::Result<DecodedPython, &'static str> {
    if raw.contains(&0) {
        return Err("NUL_BYTE");
    }
    let bom = raw.starts_with(UTF8_BOM);
    let bytes = if bom { &raw[UTF8_BOM.len()..] } else { raw };
    let text = std::str::from_utf8(bytes).map_err(|_| "ENCODING_INVALID")?;
    let cookies = encoding_cookies(text.as_bytes());
    if cookies.iter().any(|cookie| !allowed_encoding(cookie)) {
        return Err("ENCODING_UNSUPPORTED");
    }
    let normalized = cookies
        .iter()
        .map(|cookie| normalize_encoding(cookie))
        .collect::<BTreeSet<_>>();
    if normalized.len() > 1 {
        return Err("ENCODING_CONFLICT");
    }
    if bom && normalized.iter().any(|encoding| encoding != "utf8") {
        return Err("ENCODING_CONFLICT");
    }
    if normalized.contains("ascii") && !bytes.is_ascii() {
        return Err("ENCODING_INVALID");
    }
    Ok(DecodedPython {
        bytes: bytes.to_vec(),
        bom_removed: bom,
    })
}

fn encoding_cookies(bytes: &[u8]) -> Vec<String> {
    bytes
        .split(|byte| *byte == b'\n')
        .take(2)
        .filter_map(find_encoding_cookie)
        .collect()
}

fn find_encoding_cookie(line: &[u8]) -> Option<String> {
    let comment = line.iter().position(|byte| *byte == b'#')?;
    let tail = &line[comment + 1..];
    let coding = tail.windows(6).position(|window| window == b"coding")?;
    let mut cursor = coding + 6;
    while tail
        .get(cursor)
        .is_some_and(|byte| matches!(byte, b' ' | b'\t'))
    {
        cursor += 1;
    }
    if !tail
        .get(cursor)
        .is_some_and(|byte| matches!(byte, b':' | b'='))
    {
        return None;
    }
    cursor += 1;
    while tail
        .get(cursor)
        .is_some_and(|byte| matches!(byte, b' ' | b'\t'))
    {
        cursor += 1;
    }
    let start = cursor;
    while tail
        .get(cursor)
        .is_some_and(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
    {
        cursor += 1;
    }
    (cursor > start).then(|| String::from_utf8_lossy(&tail[start..cursor]).into_owned())
}

fn allowed_encoding(value: &str) -> bool {
    matches!(normalize_encoding(value).as_str(), "utf8" | "ascii")
}

fn normalize_encoding(value: &str) -> String {
    match value.to_ascii_lowercase().replace(['-', '_'], "").as_str() {
        "utf8" | "utf8sig" => "utf8".to_owned(),
        "ascii" | "usascii" => "ascii".to_owned(),
        other => other.to_owned(),
    }
}

fn contains_generated_marker(bytes: &[u8]) -> bool {
    let lower = bytes.iter().map(u8::to_ascii_lowercase).collect::<Vec<_>>();
    GENERATED_MARKERS
        .iter()
        .any(|marker| lower.windows(marker.len()).any(|window| window == *marker))
}

#[derive(Clone, Debug, Eq, PartialEq)]
enum LicenseToken {
    Id(String),
    And,
    Or,
    Left,
    Right,
}

pub(crate) fn license_allowed(expression: &str) -> bool {
    let Some(tokens) = tokenize_license(expression) else {
        return false;
    };
    let mut parser = LicenseParser {
        tokens: &tokens,
        at: 0,
    };
    parser
        .parse_or()
        .is_some_and(|allowed| allowed && parser.at == tokens.len())
}

fn tokenize_license(expression: &str) -> Option<Vec<LicenseToken>> {
    let mut tokens = Vec::new();
    let mut at = 0;
    let bytes = expression.as_bytes();
    while at < bytes.len() {
        if bytes[at].is_ascii_whitespace() {
            at += 1;
            continue;
        }
        match bytes[at] {
            b'(' => {
                tokens.push(LicenseToken::Left);
                at += 1;
            }
            b')' => {
                tokens.push(LicenseToken::Right);
                at += 1;
            }
            _ => {
                let start = at;
                while at < bytes.len()
                    && !bytes[at].is_ascii_whitespace()
                    && !matches!(bytes[at], b'(' | b')')
                {
                    at += 1;
                }
                let word = std::str::from_utf8(&bytes[start..at]).ok()?;
                tokens.push(match word {
                    "AND" => LicenseToken::And,
                    "OR" => LicenseToken::Or,
                    "WITH" => return None,
                    _ => LicenseToken::Id(word.to_owned()),
                });
            }
        }
    }
    (!tokens.is_empty()).then_some(tokens)
}

struct LicenseParser<'a> {
    tokens: &'a [LicenseToken],
    at: usize,
}

impl LicenseParser<'_> {
    fn parse_or(&mut self) -> Option<bool> {
        let mut value = self.parse_and()?;
        while self.tokens.get(self.at) == Some(&LicenseToken::Or) {
            self.at += 1;
            value |= self.parse_and()?;
        }
        Some(value)
    }

    fn parse_and(&mut self) -> Option<bool> {
        let mut value = self.parse_primary()?;
        while self.tokens.get(self.at) == Some(&LicenseToken::And) {
            self.at += 1;
            value &= self.parse_primary()?;
        }
        Some(value)
    }

    fn parse_primary(&mut self) -> Option<bool> {
        match self.tokens.get(self.at)? {
            LicenseToken::Id(id) => {
                self.at += 1;
                Some(PERMISSIVE_LICENSES.contains(&id.as_str()))
            }
            LicenseToken::Left => {
                self.at += 1;
                let value = self.parse_or()?;
                if self.tokens.get(self.at) != Some(&LicenseToken::Right) {
                    return None;
                }
                self.at += 1;
                Some(value)
            }
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encoding_rules_cover_bom_cookies_conflicts_and_nuls() {
        let utf8 = decode_python(b"# coding: UTF-8\nprint('ok')\n").unwrap();
        assert!(!utf8.bom_removed);
        let bom = decode_python(b"\xEF\xBB\xBF# coding=utf8\nprint('ok')\n").unwrap();
        assert!(bom.bom_removed);
        assert_eq!(
            decode_python(b"# coding: latin-1\n").unwrap_err(),
            "ENCODING_UNSUPPORTED"
        );
        assert_eq!(
            decode_python(b"# coding: utf8\n# coding: ascii\n\xC2\xA9").unwrap_err(),
            "ENCODING_CONFLICT"
        );
        assert_eq!(decode_python(b"print('\0')\n").unwrap_err(), "NUL_BYTE");
        assert_eq!(decode_python(b"\xFF\n").unwrap_err(), "ENCODING_INVALID");
    }

    #[test]
    fn permissive_spdx_expression_semantics_are_exact() {
        for allowed in PERMISSIVE_LICENSES {
            assert!(license_allowed(allowed));
        }
        assert!(license_allowed("MIT OR GPL-3.0-only"));
        assert!(license_allowed("MIT AND Apache-2.0"));
        assert!(!license_allowed("MIT AND GPL-3.0-only"));
        assert!(!license_allowed("Apache-2.0 WITH LLVM-exception"));
        assert!(!license_allowed("LicenseRef-private"));
        assert!(!license_allowed(""));
    }

    #[test]
    fn parser_policy_uses_only_independent_comment_ranges() {
        let bytes = b"value = 'do not edit'\n# generated by tool\npass\n";
        assert_eq!(
            evaluate_parser_policy(
                bytes,
                &ParserFacts {
                    dialect_accepted: true,
                    comment_ranges: vec![ByteRange { start: 22, end: 41 }],
                },
            )
            .unwrap(),
            ParserPolicyDecision::Rejected("GENERATED_MARKER")
        );
        assert_eq!(
            evaluate_parser_policy(
                bytes,
                &ParserFacts {
                    dialect_accepted: true,
                    comment_ranges: vec![],
                },
            )
            .unwrap(),
            ParserPolicyDecision::Accepted
        );
        let mut separate = vec![b'x'; 100];
        separate[..11].copy_from_slice(b"# generated");
        separate[12..21].copy_from_slice(b"# by tool");
        assert_eq!(
            evaluate_parser_policy(
                &separate,
                &ParserFacts {
                    dialect_accepted: true,
                    comment_ranges: vec![
                        ByteRange { start: 0, end: 11 },
                        ByteRange { start: 12, end: 21 },
                    ],
                },
            )
            .unwrap(),
            ParserPolicyDecision::Accepted
        );
    }

    #[test]
    fn parser_policy_preserves_equality_and_header_boundary() {
        let bytes = vec![b'x'; 20];
        assert_eq!(
            evaluate_parser_policy(
                &bytes,
                &ParserFacts {
                    dialect_accepted: true,
                    comment_ranges: vec![ByteRange { start: 0, end: 10 }],
                },
            )
            .unwrap(),
            ParserPolicyDecision::Accepted
        );
        let mut after_header = vec![b'x'; GENERATED_HEADER_BYTES + 32];
        after_header[GENERATED_HEADER_BYTES..GENERATED_HEADER_BYTES + 11]
            .copy_from_slice(b"do not edit");
        assert_eq!(
            evaluate_parser_policy(
                &after_header,
                &ParserFacts {
                    dialect_accepted: true,
                    comment_ranges: vec![ByteRange {
                        start: GENERATED_HEADER_BYTES,
                        end: GENERATED_HEADER_BYTES + 11,
                    }],
                },
            )
            .unwrap(),
            ParserPolicyDecision::Accepted
        );
    }

    #[test]
    fn every_generated_marker_and_size_boundary_is_exact() {
        for marker in GENERATED_MARKERS {
            let mut bytes = vec![b'x'; 200];
            bytes[0] = b'#';
            bytes[1..marker.len() + 1].copy_from_slice(marker);
            assert_eq!(
                evaluate_parser_policy(
                    &bytes,
                    &ParserFacts {
                        dialect_accepted: true,
                        comment_ranges: vec![ByteRange {
                            start: 0,
                            end: marker.len() + 1,
                        }],
                    },
                )
                .unwrap(),
                ParserPolicyDecision::Rejected("GENERATED_MARKER")
            );
        }
        assert!(!canonical_size_allowed(99));
        assert!(canonical_size_allowed(100));
        assert!(canonical_size_allowed(1_000_000));
        assert!(!canonical_size_allowed(1_000_001));
    }

    #[test]
    fn malformed_parser_ranges_fail_closed() {
        let error = evaluate_parser_policy(
            b"abcdef",
            &ParserFacts {
                dialect_accepted: true,
                comment_ranges: vec![
                    ByteRange { start: 1, end: 4 },
                    ByteRange { start: 3, end: 5 },
                ],
            },
        )
        .unwrap_err();
        assert_eq!(error.code, "PARSER_FACTS_INVALID");
    }
}
